log_level: info
email:
  approved:
    - '^.*@bah\.com$'
    - '^.*@va\.gov$'
  distro:
    to:
      - E_BIP_Platform_Prod_HealthCheck@bah.com
    cc:
      - alexander.loy@va.gov
      - jeffrey.jensen2@va.gov
  manner: smtp
  options:
    address: 'smtp.va.gov'
    port: 25
uris:
  api_server: https://api.prod8.bip.va.gov/healthz
  consul: http://prod8-consul.vault:8500/v1/status/leader
  dex: http://dex.auth:5556/healthz
  elastic_search:
    uri: http://prod8-elasticsearch-client.logging:9200/_cluster/health
    type: json
    value: status
  grafana: http://prod8-grafana.monitoring/api/health
  idm: https://idm.prod.bip.va.gov/ipa/ui/
  kibana: http://prod8-kibana.logging:443/status
  vault:
    uri: 'http://prod8-vault.vault:8200/v1/sys/health?standbyok'
    type: response_code
    response_codes:
      429:
        text: STANDBY
        health: 'pass'
      472:
        text: 'RECOVERY MODE'
        health: 'fail'
      473:
        text: 'PERFORMANCE STANDBY'
        health: 'fail'
      501:
        text: 'UNINITIALIZED'
        health: 'fail'
      503:
        text: 'SEALED'
        health: 'fail'
kubernetes:
  url: https://kubernetes.default.svc
nexus:
  repos:
    prod: 'https://container-registry.prod8.bip.va.gov/'
    stage: 'https://container-registry.stage8.bip.va.gov/'
    dev: 'https://container-registry.dev8.bip.va.gov/'
prometheus:
  url: http://prod8-prometheus-operator-prometheus.monitoring:9090
redis: "redis://:tzJryM3zh2AUN3zW@localhost:6379"
worker:
  sleep: 30
